version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: igorsilva3-tech-challenge
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always

volumes:
  postgres-data: